/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface TravelDiaryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "createDiary"
      | "getChunkCount"
      | "getDiaryCount"
      | "getDiaryEntry"
      | "getEncryptedTextChunk"
      | "protocolId"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic: "DiaryCreated" | "DiaryDecrypted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "createDiary",
    values: [BytesLike[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getChunkCount",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getDiaryCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getDiaryEntry",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEncryptedTextChunk",
    values: [AddressLike, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "protocolId",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "createDiary",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getChunkCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDiaryCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getDiaryEntry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEncryptedTextChunk",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "protocolId", data: BytesLike): Result;
}

export namespace DiaryCreatedEvent {
  export type InputTuple = [
    user: AddressLike,
    diaryId: BigNumberish,
    timestamp: BigNumberish
  ];
  export type OutputTuple = [user: string, diaryId: bigint, timestamp: bigint];
  export interface OutputObject {
    user: string;
    diaryId: bigint;
    timestamp: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace DiaryDecryptedEvent {
  export type InputTuple = [user: AddressLike, diaryId: BigNumberish];
  export type OutputTuple = [user: string, diaryId: bigint];
  export interface OutputObject {
    user: string;
    diaryId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TravelDiary extends BaseContract {
  connect(runner?: ContractRunner | null): TravelDiary;
  waitForDeployment(): Promise<this>;

  interface: TravelDiaryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  createDiary: TypedContractMethod<
    [encryptedTextChunks: BytesLike[], inputProofs: BytesLike[]],
    [void],
    "nonpayable"
  >;

  getChunkCount: TypedContractMethod<
    [user: AddressLike, diaryId: BigNumberish],
    [bigint],
    "view"
  >;

  getDiaryCount: TypedContractMethod<[user: AddressLike], [bigint], "view">;

  getDiaryEntry: TypedContractMethod<
    [user: AddressLike, diaryId: BigNumberish],
    [[bigint, boolean] & { timestamp: bigint; exists: boolean }],
    "view"
  >;

  getEncryptedTextChunk: TypedContractMethod<
    [user: AddressLike, diaryId: BigNumberish, chunkIndex: BigNumberish],
    [string],
    "view"
  >;

  protocolId: TypedContractMethod<[], [bigint], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "createDiary"
  ): TypedContractMethod<
    [encryptedTextChunks: BytesLike[], inputProofs: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getChunkCount"
  ): TypedContractMethod<
    [user: AddressLike, diaryId: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getDiaryCount"
  ): TypedContractMethod<[user: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getDiaryEntry"
  ): TypedContractMethod<
    [user: AddressLike, diaryId: BigNumberish],
    [[bigint, boolean] & { timestamp: bigint; exists: boolean }],
    "view"
  >;
  getFunction(
    nameOrSignature: "getEncryptedTextChunk"
  ): TypedContractMethod<
    [user: AddressLike, diaryId: BigNumberish, chunkIndex: BigNumberish],
    [string],
    "view"
  >;
  getFunction(
    nameOrSignature: "protocolId"
  ): TypedContractMethod<[], [bigint], "view">;

  getEvent(
    key: "DiaryCreated"
  ): TypedContractEvent<
    DiaryCreatedEvent.InputTuple,
    DiaryCreatedEvent.OutputTuple,
    DiaryCreatedEvent.OutputObject
  >;
  getEvent(
    key: "DiaryDecrypted"
  ): TypedContractEvent<
    DiaryDecryptedEvent.InputTuple,
    DiaryDecryptedEvent.OutputTuple,
    DiaryDecryptedEvent.OutputObject
  >;

  filters: {
    "DiaryCreated(address,uint256,uint256)": TypedContractEvent<
      DiaryCreatedEvent.InputTuple,
      DiaryCreatedEvent.OutputTuple,
      DiaryCreatedEvent.OutputObject
    >;
    DiaryCreated: TypedContractEvent<
      DiaryCreatedEvent.InputTuple,
      DiaryCreatedEvent.OutputTuple,
      DiaryCreatedEvent.OutputObject
    >;

    "DiaryDecrypted(address,uint256)": TypedContractEvent<
      DiaryDecryptedEvent.InputTuple,
      DiaryDecryptedEvent.OutputTuple,
      DiaryDecryptedEvent.OutputObject
    >;
    DiaryDecrypted: TypedContractEvent<
      DiaryDecryptedEvent.InputTuple,
      DiaryDecryptedEvent.OutputTuple,
      DiaryDecryptedEvent.OutputObject
    >;
  };
}
